apiVersion: apps/v1
kind: Deployment
metadata:
  name: kappa-agg
  labels:
    app: kappa
spec:
  selector:
    matchLabels:
      app: kappa-agg
  template:
    metadata:
      labels:
        app: kappa-agg
    spec:
      containers:
        - name: kappa
          image: kentik/kappa
          command: ["/opt/kentik/kappa/kappa"]
          args:
            - "-v"
            - "agg"
            - "0.0.0.0:4000"
          env:
            - name: KENTIK_CLOUDPROVIDER
              valueFrom:
                configMapKeyRef:
                  name: kube-config
                  key: cloudprovider
            - name: KENTIK_CLOUDREGION
              valueFrom:
                configMapKeyRef:
                  name: kube-config
                  key: cloudregion
            - name: KENTIK_DEVICE
              valueFrom:
                configMapKeyRef:
                  name: kappa-config
                  key: device
            - name: KENTIK_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: kube-config
                  key: environment
            - name: KENTIK_EMAIL
              valueFrom:
                secretKeyRef:
                  name: kentik-api-secrets
                  key: email
            - name: KENTIK_PLAN
              valueFrom:
                configMapKeyRef:
                  name: kappa-config
                  key: plan
            - name: KENTIK_REGION
              valueFrom:
                configMapKeyRef:
                  name: kappa-config
                  key: region
            - name: KENTIK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kentik-api-secrets
                  key: token
            - name: KENTIK_UUID
              valueFrom:
                configMapKeyRef:
                  name: kube-config
                  key: uuid
            - name: RUST_LIB_BACKTRACE
              value: "1"
          ports:
            - containerPort: 4000
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: kappa-agg
  labels:
    app: kappa
spec:
  type: ClusterIP
  selector:
    app: kappa-agg
  ports:
    - name: agg
      protocol: TCP
      port: 4000
    - name: aug
      protocol: TCP
      port: 4001
