apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kappa-agent
  labels:
    app: kappa
spec:
  selector:
    matchLabels:
      app: kappa
  template:
    metadata:
      labels:
        app: kappa
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: kappa
          image: kentik/kappa
          securityContext:
            privileged: true
          command: ["/opt/kentik/kappa/kappa"]
          args:
            - "-v"
            - "agent"
            - "--node"
            - "$(KAPPA_NODE_NAME)"
            - "--capture"
            - "$(capture)"
            - "--sample"
            - "1:4"
            - "--bytecode"
            - "$(bytecode)"
            - "$(KAPPA_AGG_SERVICE_HOST):4000"
          envFrom:
            - configMapRef:
                name: kappa-config
          env:
            - name: KAPPA_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RUST_LIB_BACKTRACE
              value: "1"
          volumeMounts:
            - name: debugfs
              mountPath: /sys/kernel/debug
            - name: bytecode
              mountPath: /bytecode
            - name: init
              mountPath: /init
          imagePullPolicy: Always
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: bytecode
          configMap:
            name: kappa-bytecode
        - name: init
          configMap:
            name: kappa-init
---
