apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemeta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemeta
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods", "services"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubemeta
subjects:
  - kind: ServiceAccount
    name: kubemeta
    namespace: default
roleRef:
  kind: ClusterRole
  name: kubemeta
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemeta-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubemeta
  template:
    metadata:
      labels:
        app: kubemeta
    spec:
      serviceAccountName: kubemeta
      containers:
        - name: kubemeta
          image: kentik/kubemeta:latest
          args: ["--check-interval", "20"]
          imagePullPolicy: Always