namespace: kentik
resources:
  - namespace.yml
  - kappa-agent.yml
  - kappa-agg.yml
  - kubeinfo.yml
  - kubemeta.yml
images:
  - name: kentik/kappa
    newTag: "1.1.1"
  - name: kentik/kubeinfo
    newTag: "1.0.1"
  - name: kentik/kubemeta
    newTag: __KUBEMETA_VERSION__
configMapGenerator:
  - name: kappa-config
    literals:
      - capture=__CAPTURE__
      - device=__CLUSTER__
      - region=__ACCOUNTREGION__
      - plan=__PLAN__
      - sampleratio=__KAPPA_SAMPLE_RATIO__
      - bytecode=x86_64/kappa_bpf-ubuntu-5.4.o
  - name: kappa-init
    files:
      - init/exec
      - init/fetch
      - init/trace
  - name: kube-config
    literals:
      - cloudprovider=__CLOUDPROVIDER__
      - grpcendpoint=__GRPCENDPOINT__
      - maxgrpcpayload=__MAXGRPCPAYLOAD__
patchesJson6902:
#   - target:
#       group: "apps"
#       version: v1
#       kind: DaemonSet
#       name: kappa-agent
#     path: kappa-bytecode.yml
secretGenerator:
  - name: kentik-api-secrets
    literals:
      - email=__EMAIL__
      - token=__TOKEN__
