namespace: kentik
resources:
  - namespace.yml
  - kappa-agent.yml
  - kappa-agg.yml
  - kubemeta.yml
images:
  - name: kentik/kappa
    newTag: "1.1.1"
  - name: kentik/kubeinfo
    newTag: "1.0.1"
configMapGenerator:
  - name: kappa-config
    literals:
      - capture=ens3|veth.*
      - device=__DEVICE__
      - region=US
      - plan=__PLAN__
      - bytecode=x86_64/kappa_bpf-ubuntu-5.4.o
  - name: kappa-init
    files:
      - init/exec
      - init/fetch
      - init/trace
patchesJson6902:
#   - target:
#       group: "apps"
#       version: v1
#       kind: DaemonSet
#       name: kappa-agent
#     path: kappa-bytecode.yml
secretGenerator:
  - name: kentik-api-secrets
    literals:
      - email=__EMAIL__
      - token=__TOKEN__
