namespace: kentik
resources:
  - namespace.yml
  - kappa-agent.yml
  - kappa-agg.yml
  - kubeinfo.yml
images:
  - name: kentik/kappa
    newTag: "1.1.0"
  - name: kentik/kubeinfo
    newTag: "1.0.0"
configMapGenerator:
  - name: kappa-config
    literals:
      - capture=ens3|veth.*
      - device=kappa_test
      - region=US
      - plan=1234
      - bytecode=x86_64/kappa_bpf-ubuntu-5.4.o
  - name: kappa-init
    files:
      - init/exec
      - init/fetch
      - init/trace
patchesJson6902:
#   - target:
#       group: "apps"
#       version: v1
#       kind: DaemonSet
#       name: kappa-agent
#     path: kappa-bytecode.yml
secretGenerator:
  - name: kentik-api-secrets
    literals:
      - email=test@example.com
      - token=asdf1234
