namespace: kentik
resources:
  - namespace.yml
  - kappa-agent.yml
  - kappa-agg.yml
  - kubeinfo.yml
  - kubemeta.yml
images:
  - name: kentik/kappa
    newTag: "1.1.4"
  - name: kentik/kubeinfo
    newTag: "1.0.1"
  - name: kentik/kubemeta
    newTag: __KUBEMETA_VERSION__
configMapGenerator:
  - name: kappa-config
    literals:
      - capture=__CAPTURE__
      - device=__CLUSTER__
      - region=__ACCOUNTREGION__
      - plan=__PLAN__
      - sampleratio=__KAPPA_SAMPLE_RATIO__
      - bytecode=x86_64/kappa_bpf-ubuntu-5.4.o
  - name: kappa-init
    files:
      - init/exec
      - init/fetch
      - init/trace
  - name: kube-config
    literals:
      - cloudprovider=__CLOUDPROVIDER__
      - cloudregion=__CLOUDREGION__
      - environment=__ENVIRONMENT__
      - grpcendpoint=__GRPCENDPOINT__
      - maxgrpcpayload=__MAXGRPCPAYLOAD__
      - uuid=__UUID__
# patchesJson6902:
#   - target:
#       group: "apps"
#       version: v1
#       kind: DaemonSet
#       name: kappa-agent
#     path: kappa-bytecode.yml
patches:
  - target:
      kind: DaemonSet
      name: kappa-agent
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: __KAPPA_AGENT_CPU_REQUEST__
            memory: __KAPPA_AGENT_MEM_REQUEST__
          limits:
            cpu: __KAPPA_AGENT_CPU_LIMIT__
            memory: __KAPPA_AGENT_MEM_LIMIT__
  - target:
      kind: Deployment
      name: kappa-agg
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: __KAPPA_AGG_CPU_REQUEST__
            memory: __KAPPA_AGG_MEM_REQUEST__
          limits:
            cpu: __KAPPA_AGG_CPU_LIMIT__
            memory: __KAPPA_AGG_MEM_LIMIT__
  - target:
      kind: Deployment
      name: kubeinfo
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: __KUBEINFO_CPU_REQUEST__
            memory: __KUBEINFO_MEM_REQUEST__
          limits:
            cpu: __KUBEINFO_CPU_LIMIT__
            memory: __KUBEINFO_MEM_LIMIT__
  - target:
      kind: Deployment
      name: kubemeta-deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: __KUBEMETA_CPU_REQUEST__
            memory: __KUBEMETA_MEM_REQUEST__
          limits:
            cpu: __KUBEMETA_CPU_LIMIT__
            memory: __KUBEMETA_MEM_LIMIT__
secretGenerator:
  - name: kentik-api-secrets
    literals:
      - email=__EMAIL__
      - token=__TOKEN__
