namespace: kentik
resources:
  - kappa-agent.yml
  - kappa-agg.yml
  - kubeinfo.yml
images:
  - name: kentik/kappa
    newTag: "latest"
  - name: kentik/kubeinfo
    newTag: "1.0.0"
configMapGenerator:
  - name: kappa-config
    literals:
      - capture=ens3|veth.*
      - device=kappa_test
      - plan=1234
      - bytecode=/bytecode/kappa_bpf-ubuntu-5.4.o
  - name: kappa-bytecode
    files:
      - bytecode/kappa_bpf-ubuntu-5.4.o
  - name: kappa-init
    files:
      - init/exec
      - init/trace
secretGenerator:
  - name: kentik-api-secrets
    literals:
      - email=test@example.com
      - token=asdf1234
